# Generated by Django 2.2.10 on 2020-02-06 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0002_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='hits',
            field=models.IntegerField(default=0, verbose_name='瀏覽次數'),
        ),
    ]
